# Generated by Django 2.1.5 on 2019-03-08 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.TimeField()),
                ('present', models.BooleanField(default=False)),
                ('notes', models.CharField(default='meeting notes', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mentor_name', models.CharField(max_length=20)),
                ('mentor_gender', models.CharField(help_text='Enter F or M', max_length=10, null=True)),
                ('mentor_address', models.CharField(max_length=200)),
                ('mentor_city', models.CharField(max_length=50)),
                ('mentor_state', models.CharField(max_length=50)),
                ('mentor_zipcode', models.CharField(max_length=10)),
                ('mentor_email', models.EmailField(max_length=100)),
                ('mentor_phoneno', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('mentor_image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_dob', models.DateField()),
                ('stud_gender', models.CharField(help_text='Enter F or M', max_length=10, null=True)),
                ('stud_address', models.CharField(max_length=200)),
                ('stud_city', models.CharField(max_length=50)),
                ('stud_state', models.CharField(max_length=50)),
                ('stud_zipcode', models.CharField(max_length=10)),
                ('stud_email', models.EmailField(max_length=100)),
                ('stud_phoneno', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('stud_image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stud_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='mentor.School')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(db_index=True, max_length=10)),
                ('week_startdate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorname', to='mentor.Mentor'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='mentor.Semester'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='stud_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='mentor.Student'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeknumber', to='mentor.Week'),
        ),
    ]
